### ISSUE TITLE
 GT-AUG func problems

### ISSUE THREAD

**Issue by majaya** [poodarchu/Det3D#146]
I'd like to ask some questions，when I train model using Det3D project, I find that GT-AUG strategy is not exactly precise sometimes. the GT-AUG func in Det3D project only take account collision with the origin gt boxes, but the boxes that we get from gt_database sometimes will embedded in the wall, bush or other entity in current point cloud frame, also, some boxes will get off the ground and hanging in the air. Is it necessary to consider avoiding this situation. Does this affect training？

**Comment by poodarchu** [comment]
According to my experiments, this problem does indeed exist, but it has minor effect on the final results. I think it might due to the gain of GT-AUG w.r.t. number of instances overweight the side-effect caused by the collision problem. To avoid this collision, the segmentation map is required, or rough approximation of the wall are required.
